project:
  type: website

website:
  title: "FCC BDC EDA"
  repo-url: https://github.com/ruralinnovation/proj-fcc-report
  repo-actions: [edit, issue]
  navbar: 
    left:
      - href: index.qmd
        text: Home
      - about.qmd

  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "EDA"
        contents:
          - zero_dl_up.qmd
          - FCC_provider_list.qmd
          - isp_eda.qmd
          - ntia_test.qmd
          - ms-eda.qmd
          - road-eda.qmd
          - rdof.qmd
          - fcc_funding.qmd
          - hubb.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



