project:
  type: website

website:
  title: "FCC BDC EDA"
  repo-url: https://github.com/ruralinnovation/proj-fcc-report
  repo-actions: [edit, issue]
  navbar: 
    left:
      - href: index.qmd
        text: Home
      - about.qmd

  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "FCC Data"
        contents:
          - nbm_data.qmd 
          - FCC_provider_list.qmd
          - isp_eda.qmd
          - fcc_funding.qmd
          - zero_dl_up.qmd
          - ntia_test.qmd
      - section: "Other data sources"
        contents:
          - road-eda.qmd
          - ms-eda.qmd
      - section: "Metadata and Storage"
        contents:
          - metadata_raw_nbm.qmd 

format:
  html:
    theme: cosmo
    css: styles.css
    grid:
      sidebar-width: 250px
      body-width: 1100px
      margin-width: 250px
    toc: true



