project:
  type: website

website:
  title: "FCC NBM EDA"
  repo-url: https://github.com/ruralinnovation/proj-fcc-report
  repo-actions: [edit, issue]
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - zero_dl_up.qmd
      - isp_eda.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



