---
title: "FCC Funding Map"
date: last-modified
format: 
  html:
    code-fold: true
engine: knitr
---

Link: https://fundingmap.fcc.gov/home

Documentation: https://us-fcc.app.box.com/v/bfm-data-downloads-output

The download page has two tabs:

- [Funding data](https://fundingmap.fcc.gov/data-download/funding-data)

- [Unserved/unfunded](https://fundingmap.fcc.gov/data-download/unserved-data)

# Funding data

## Program Data 

It is organized by Agency and can be downloaded by program (`fundingdata_projectXXXX`) or for all projects in a program  (`fundingdata_programXX`).

it will have a `csv` about the program. For example RDOF is just a two rows csv, header included.

## Project Data

They are defining 3 types of projects: 

- Defined by Area

- Defined by list of locations

- Defined by Middle Mile

All of those type of project will have a Project Attribute Information table (`areaattributes_program` or `locationattributes_program`). The structure of those files are close but not similar has columns related to location (`build_req`, `loc_plan`, `loc_sup`). 

For example the one for RDOF (`areaattributes_program24_J23_12feb2024.csv`) has 474 rows (inclunding headers ie 473 projects). 

Area project will have an associated `areapolygons_XXX.gpkg`. A quick glance on the one from RDOF show full valid geometries with an expected number of rows (473).

Location project has instead of a gpkg a csv with location_id and lat/long (and address) !






