---
title: "Microsoft Building footprint"
date: last-modified
format: 
  html:
    code-fold: true
engine: knitr
---

# MS Building Foot print

## Overview

MS used satellite data (from multiple campains/vintage) to get the footprint of buildings. 

They are classifying pixels that are supposed to be part of a buildings (segmentation using a neural network) and then convert pixels to a shape. 

It exists [worldwide](https://github.com/microsoft/GlobalMLBuildingFootprints) and for [US states](https://github.com/Microsoft/USBuildingFootprints?tab=readme-ov-file). 

- We have processed the 51 states 

- Additional works will be required for PR and US territories (parts of workflow from the US states can be reused).

The precision of the model vary depending on the region: the Carribean is at 92,2% and the US at 98.5%. The rate of false positive is 1% for the US and 1.8% for the Carribean. (Oceania was not provided)

The license is [ODbL](https://github.com/Microsoft/USBuildingFootprints?tab=License-1-ov-file).

## Buildings to BSL?

Buildings are shapes, BSL are points. We converted the buildings to single point (arbitrary: the first vertex of the shape) to lower the amout of data. 

The number of buildings reported for 51 states is: 130 099 920

While is the number of BSL is: 114 074 438 

### Other potential sources:

- OpenStreetMap
  
- [FCC staff estimates](https://www.fcc.gov/staff-block-estimates): at census block level (only for US 51) 

- ACS households

# Should this information be provided and how?

**What could be the use cases?**

We can: 

- Provide the count per census block of MS building footprint and the user  

- Add the dot to the map (it has cost: information "overload", documentation about is needed)

- Add a "confidence" about it (will always be statitical)

::: {.column-margin}
How this data help BEAD applicant?
:::

## MS building footprint in VT

We can count those points per block and compare to the number of location than FCC is descriving.

After that can build a small model that will provide either an estimate of BSL given MS footrpint and how confidant the model is. 

```{r}
#| label: quick lm model for bsl
#| warning: false
vt <- read.csv("data/vt_ms.csv")
vt$tot_loc <-as.numeric(vt$tot_loc) 
vt$tot_loc <- ifelse(is.na(vt$tot_loc), 0, vt$tot_loc)

lm_ms <- lm(cnt_ms ~ tot_loc, data = vt)
pot_val <- seq(min(vt$tot_loc), max(vt$tot_loc), by = 0.025)
conf_interval <- predict(lm_ms, newdata = data.frame( tot_loc = pot_val) ,
						 interval = "prediction", level = 0.95)

plot(vt$cnt_ms, vt$tot_loc,  col = "#DF536B50", asp = 1, 
xlab = "cnt of MS buildings", ylab = "cnt of fcc locations") 
abline(lm_ms, col = 4)
abline(1:500, 1:500, col = "black")
lines(pot_val, conf_interval[, "lwr"], col = "blue", lty = 2)
lines(pot_val, conf_interval[, "upr"], col =" blue", lty = 2)
```

- my model (just a linear one) is probably bad (log should correct that)

- still strong relation

- the model is "overconfidant" 

- it seems MS has **more** locations (285333, versus 352618) 